-- MySQL Script generated by MySQL Workbench
-- 08/12/16 02:00:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema greenic_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `greenic_db` ;

-- -----------------------------------------------------
-- Schema greenic_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `greenic_db` DEFAULT CHARACTER SET utf8 ;
USE `greenic_db` ;

-- -----------------------------------------------------
-- Table `greenic_db`.`greenic_activity_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenic_db`.`greenic_activity_type` (
  `activity_type_id` INT(11) NOT NULL AUTO_INCREMENT,
  `activity_type_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`activity_type_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `greenic_db`.`greenic_member_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenic_db`.`greenic_member_type` (
  `member_type_id` INT(11) NOT NULL AUTO_INCREMENT,
  `member_type_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`member_type_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `greenic_db`.`greenic_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenic_db`.`greenic_status` (
  `status_id` INT(11) NOT NULL AUTO_INCREMENT,
  `status_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `greenic_db`.`greenic_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenic_db`.`greenic_member` (
  `member_id` INT(11) NOT NULL AUTO_INCREMENT,
  `member_email` VARCHAR(100) NOT NULL,
  `member_firstname` VARCHAR(200) NOT NULL,
  `member_lastname` VARCHAR(200) NULL DEFAULT NULL,
  `member_password` VARCHAR(512) NOT NULL,
  `member_img_path` VARCHAR(512) NULL DEFAULT NULL,
  `member_address` VARCHAR(400) NULL DEFAULT NULL,
  `member_province` VARCHAR(300) NULL DEFAULT NULL,
  `member_district` VARCHAR(300) NULL DEFAULT NULL,
  `member_sub_district` VARCHAR(300) NULL DEFAULT NULL,
  `member_token` VARCHAR(512) NULL DEFAULT NULL,
  `member_regis_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `member_verify_time` TIMESTAMP NULL DEFAULT NULL,
  `member_type_id` INT(11) NOT NULL,
  `member_status_id` INT(11) NOT NULL,
  PRIMARY KEY (`member_id`),
  UNIQUE INDEX `member_email_UNIQUE` (`member_email` ASC),
  INDEX `fk_greenic_member_greenic_member_type2_idx` (`member_type_id` ASC),
  INDEX `fk_greenic_member_greenic_status1_idx` (`member_status_id` ASC),
  CONSTRAINT `fk_greenic_member_greenic_member_type2`
    FOREIGN KEY (`member_type_id`)
    REFERENCES `greenic_db`.`greenic_member_type` (`member_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_greenic_member_greenic_status1`
    FOREIGN KEY (`member_status_id`)
    REFERENCES `greenic_db`.`greenic_status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `greenic_db`.`greenic_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenic_db`.`greenic_admin` (
  `admin_id` INT(11) NOT NULL AUTO_INCREMENT,
  `admin_username` VARCHAR(20) NOT NULL,
  `admin_level` INT(11) NOT NULL,
  `admin_member_id` INT(11) NOT NULL,
  PRIMARY KEY (`admin_id`),
  UNIQUE INDEX `admin_username_UNIQUE` (`admin_username` ASC),
  INDEX `fk_greenic_admin_greenic_member1_idx` (`admin_member_id` ASC),
  CONSTRAINT `fk_greenic_admin_greenic_member1`
    FOREIGN KEY (`admin_member_id`)
    REFERENCES `greenic_db`.`greenic_member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `greenic_db`.`greenic_article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenic_db`.`greenic_article` (
  `article_id` INT(11) NOT NULL AUTO_INCREMENT,
  `article_headline` VARCHAR(600) NOT NULL,
  `article_content` TEXT NOT NULL,
  `article_view` INT(11) NOT NULL DEFAULT '0',
  `article_member_id` INT(11) NOT NULL,
  PRIMARY KEY (`article_id`),
  INDEX `fk_greenic_article_greenic_member1_idx` (`article_member_id` ASC),
  CONSTRAINT `fk_greenic_article_greenic_member1`
    FOREIGN KEY (`article_member_id`)
    REFERENCES `greenic_db`.`greenic_member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `greenic_db`.`greenic_project_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenic_db`.`greenic_project_type` (
  `project_type_id` INT(11) NOT NULL AUTO_INCREMENT,
  `project_type_name` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`project_type_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `greenic_db`.`greenic_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenic_db`.`greenic_category` (
  `category_id` INT(11) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(256) NOT NULL,
  `category_description` VARCHAR(256) NOT NULL,
  `category_project_type_id` INT(11) NOT NULL,
  `category_master_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`),
  INDEX `fk_greenic_category_greenic_project_type1_idx` (`category_project_type_id` ASC),
  INDEX `fk_greenic_category_greenic_category1_idx` (`category_master_id` ASC),
  CONSTRAINT `fk_greenic_category_greenic_category1`
    FOREIGN KEY (`category_master_id`)
    REFERENCES `greenic_db`.`greenic_category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_greenic_category_greenic_project_type1`
    FOREIGN KEY (`category_project_type_id`)
    REFERENCES `greenic_db`.`greenic_project_type` (`project_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `greenic_db`.`greenic_chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenic_db`.`greenic_chat` (
  `chat_id` INT(11) NOT NULL AUTO_INCREMENT,
  `chat_sender_id` INT(11) NOT NULL,
  `chat_receiver_id` INT(11) NOT NULL,
  `chat_message` TEXT NOT NULL,
  `chat_sendtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `chat_seentime` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`chat_id`),
  INDEX `fk_greenic_chat_greenic_member1_idx` (`chat_sender_id` ASC),
  INDEX `fk_greenic_chat_greenic_member2_idx` (`chat_receiver_id` ASC),
  CONSTRAINT `fk_greenic_chat_greenic_member1`
    FOREIGN KEY (`chat_sender_id`)
    REFERENCES `greenic_db`.`greenic_member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_greenic_chat_greenic_member2`
    FOREIGN KEY (`chat_receiver_id`)
    REFERENCES `greenic_db`.`greenic_member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `greenic_db`.`greenic_province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenic_db`.`greenic_province` (
  `province_id` INT(5) NOT NULL AUTO_INCREMENT,
  `province_code` VARCHAR(2) NULL DEFAULT NULL,
  `province_name` VARCHAR(150) NULL DEFAULT NULL,
  `province_geo_id` INT(5) NULL DEFAULT NULL,
  PRIMARY KEY (`province_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 78
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `greenic_db`.`greenic_district`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenic_db`.`greenic_district` (
  `district_id` INT(5) NOT NULL AUTO_INCREMENT,
  `district_code` VARCHAR(4) NULL DEFAULT NULL,
  `district_name` VARCHAR(150) NULL DEFAULT NULL,
  `district_geo_id` INT(5) NULL DEFAULT NULL,
  `district_province_id` INT(5) NOT NULL,
  PRIMARY KEY (`district_id`),
  INDEX `fk_greenic_district_greenic_province1_idx` (`district_province_id` ASC),
  CONSTRAINT `fk_greenic_district_greenic_province1`
    FOREIGN KEY (`district_province_id`)
    REFERENCES `greenic_db`.`greenic_province` (`province_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1007
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `greenic_db`.`greenic_farm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenic_db`.`greenic_farm` (
  `farm_id` INT(11) NOT NULL AUTO_INCREMENT,
  `farm_name` VARCHAR(300) NOT NULL,
  `farm_provice` VARCHAR(256) NOT NULL,
  `farm_district` VARCHAR(256) NOT NULL,
  `farm_sub_district` VARCHAR(200) NULL DEFAULT NULL,
  `farm_address` VARCHAR(600) NOT NULL,
  `farm_member_id` INT(11) NOT NULL,
  `farm_status_id` INT(11) NOT NULL,
  PRIMARY KEY (`farm_id`),
  INDEX `fk_greenic_farm_greenic_member1_idx` (`farm_member_id` ASC),
  INDEX `fk_greenic_farm_greenic_status1_idx` (`farm_status_id` ASC),
  CONSTRAINT `fk_greenic_farm_greenic_member1`
    FOREIGN KEY (`farm_member_id`)
    REFERENCES `greenic_db`.`greenic_member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_greenic_farm_greenic_status1`
    FOREIGN KEY (`farm_status_id`)
    REFERENCES `greenic_db`.`greenic_status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `greenic_db`.`greenic_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenic_db`.`greenic_project` (
  `project_id` INT(11) NOT NULL AUTO_INCREMENT,
  `project_name` VARCHAR(300) NOT NULL,
  `project_detail` TEXT NOT NULL,
  `project_location` VARCHAR(500) NOT NULL,
  `project_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `project_startdate` DATETIME NOT NULL,
  `project_enddate` DATETIME NULL DEFAULT NULL,
  `project_selldate` DATETIME NULL DEFAULT NULL,
  `project_quantity` VARCHAR(15) NULL DEFAULT NULL,
  `project_ppu` VARCHAR(200) NULL DEFAULT NULL,
  `project_view` INT(11) NULL DEFAULT NULL,
  `project_category_id` INT(11) NOT NULL,
  `project_farm_id` INT(11) NOT NULL,
  `project_status_id` INT(11) NOT NULL,
  PRIMARY KEY (`project_id`),
  INDEX `fk_greenic_project_greenic_category1_idx` (`project_category_id` ASC),
  INDEX `fk_greenic_project_greenic_farm1_idx` (`project_farm_id` ASC),
  INDEX `fk_greenic_project_greenic_status1_idx` (`project_status_id` ASC),
  CONSTRAINT `fk_greenic_project_greenic_category1`
    FOREIGN KEY (`project_category_id`)
    REFERENCES `greenic_db`.`greenic_category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_greenic_project_greenic_farm1`
    FOREIGN KEY (`project_farm_id`)
    REFERENCES `greenic_db`.`greenic_farm` (`farm_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_greenic_project_greenic_status1`
    FOREIGN KEY (`project_status_id`)
    REFERENCES `greenic_db`.`greenic_status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `greenic_db`.`greenic_follow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenic_db`.`greenic_follow` (
  `follow_id` INT(11) NOT NULL AUTO_INCREMENT,
  `follow_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `follow_member_id` INT(11) NOT NULL,
  `follow_project_id` INT(11) NULL DEFAULT NULL,
  `follow_farm_id` INT(11) NULL DEFAULT NULL,
  `follow_farmer_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`follow_id`),
  INDEX `fk_greenic_follow_greenic_member1_idx` (`follow_member_id` ASC),
  INDEX `fk_greenic_follow_greenic_project1_idx` (`follow_project_id` ASC),
  INDEX `fk_greenic_follow_greenic_farm1_idx` (`follow_farm_id` ASC),
  INDEX `fk_greenic_follow_greenic_member2_idx` (`follow_farmer_id` ASC),
  CONSTRAINT `fk_greenic_follow_greenic_farm1`
    FOREIGN KEY (`follow_farm_id`)
    REFERENCES `greenic_db`.`greenic_farm` (`farm_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_greenic_follow_greenic_member1`
    FOREIGN KEY (`follow_member_id`)
    REFERENCES `greenic_db`.`greenic_member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_greenic_follow_greenic_member2`
    FOREIGN KEY (`follow_farmer_id`)
    REFERENCES `greenic_db`.`greenic_member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_greenic_follow_greenic_project1`
    FOREIGN KEY (`follow_project_id`)
    REFERENCES `greenic_db`.`greenic_project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `greenic_db`.`greenic_notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenic_db`.`greenic_notification` (
  `notification_id` INT(11) NOT NULL AUTO_INCREMENT,
  `noticfication_message` VARCHAR(300) NULL DEFAULT NULL,
  `notification_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `notification_notice` TINYINT(2) NOT NULL,
  `notification_member_id` INT(11) NOT NULL,
  `notification_project_id` INT(11) NOT NULL,
  `notification_activity_type_id` INT(11) NOT NULL,
  PRIMARY KEY (`notification_id`),
  INDEX `fk_greenic_notification_greenic_member1_idx` (`notification_member_id` ASC),
  INDEX `fk_greenic_notification_greenic_project1_idx` (`notification_project_id` ASC),
  INDEX `fk_greenic_notification_greenic_activity_type1_idx` (`notification_activity_type_id` ASC),
  CONSTRAINT `fk_greenic_notification_greenic_activity_type1`
    FOREIGN KEY (`notification_activity_type_id`)
    REFERENCES `greenic_db`.`greenic_activity_type` (`activity_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_greenic_notification_greenic_member1`
    FOREIGN KEY (`notification_member_id`)
    REFERENCES `greenic_db`.`greenic_member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_greenic_notification_greenic_project1`
    FOREIGN KEY (`notification_project_id`)
    REFERENCES `greenic_db`.`greenic_project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `greenic_db`.`greenic_shipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenic_db`.`greenic_shipment` (
  `shipment_id` INT(11) NOT NULL AUTO_INCREMENT,
  `shipment_name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`shipment_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `greenic_db`.`greenic_product_shipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenic_db`.`greenic_product_shipment` (
  `product_shipment_Id` INT(11) NOT NULL AUTO_INCREMENT,
  `product_shipment_project_id` INT(11) NOT NULL,
  `product_shipment_shipment_id` INT(11) NOT NULL,
  PRIMARY KEY (`product_shipment_Id`),
  INDEX `fk_greenic_product_shipment_greenic_project1_idx` (`product_shipment_project_id` ASC),
  INDEX `fk_greenic_product_shipment_greenic_shipment1_idx` (`product_shipment_shipment_id` ASC),
  CONSTRAINT `fk_greenic_product_shipment_greenic_project1`
    FOREIGN KEY (`product_shipment_project_id`)
    REFERENCES `greenic_db`.`greenic_project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_greenic_product_shipment_greenic_shipment1`
    FOREIGN KEY (`product_shipment_shipment_id`)
    REFERENCES `greenic_db`.`greenic_shipment` (`shipment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `greenic_db`.`greenic_project_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenic_db`.`greenic_project_post` (
  `project_post_id` INT(11) NOT NULL AUTO_INCREMENT,
  `project_post_caption` VARCHAR(500) NOT NULL,
  `project_post_detail` VARCHAR(500) NULL DEFAULT NULL,
  `project_post_img` VARCHAR(256) NOT NULL,
  `project_post_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `project_post_project_id` INT(11) NOT NULL,
  PRIMARY KEY (`project_post_id`),
  INDEX `fk_greenic_project_post_greenic_project1_idx` (`project_post_project_id` ASC),
  CONSTRAINT `fk_greenic_project_post_greenic_project1`
    FOREIGN KEY (`project_post_project_id`)
    REFERENCES `greenic_db`.`greenic_project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `greenic_db`.`greenic_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenic_db`.`greenic_review` (
  `review_id` INT(11) NOT NULL AUTO_INCREMENT,
  `review_rate` INT(11) NOT NULL,
  `review_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `review_buydate` DATETIME NOT NULL,
  `review_comment` VARCHAR(600) NULL DEFAULT NULL,
  `review_member_id` INT(11) NOT NULL,
  `review_project_id` INT(11) NOT NULL,
  PRIMARY KEY (`review_id`),
  INDEX `fk_greenic_review_greenic_member1_idx` (`review_member_id` ASC),
  INDEX `fk_greenic_review_greenic_project1_idx` (`review_project_id` ASC),
  CONSTRAINT `fk_greenic_review_greenic_member1`
    FOREIGN KEY (`review_member_id`)
    REFERENCES `greenic_db`.`greenic_member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_greenic_review_greenic_project1`
    FOREIGN KEY (`review_project_id`)
    REFERENCES `greenic_db`.`greenic_project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `greenic_db`.`greenic_sub_district`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenic_db`.`greenic_sub_district` (
  `sub_district_id` INT(5) NOT NULL,
  `sub_district_code` VARCHAR(6) NULL DEFAULT NULL,
  `sub_district_name` VARCHAR(150) NULL DEFAULT NULL,
  `sub_district_district_id` INT(5) NOT NULL,
  `sub_district_province_id` INT(5) NOT NULL,
  `sub_district_geo_id` INT(5) NULL DEFAULT NULL,
  PRIMARY KEY (`sub_district_id`),
  INDEX `fk_greenic_sub_district_greenic_province1_idx` (`sub_district_province_id` ASC),
  INDEX `fk_greenic_sub_district_greenic_district1_idx` (`sub_district_district_id` ASC),
  CONSTRAINT `fk_greenic_sub_district_greenic_district1`
    FOREIGN KEY (`sub_district_district_id`)
    REFERENCES `greenic_db`.`greenic_district` (`district_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_greenic_sub_district_greenic_province1`
    FOREIGN KEY (`sub_district_province_id`)
    REFERENCES `greenic_db`.`greenic_province` (`province_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `greenic_db`.`greenic_vote_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenic_db`.`greenic_vote_review` (
  `vote_review_id` INT(11) NOT NULL AUTO_INCREMENT,
  `vote_review_agree` TINYINT(2) NOT NULL,
  `vote_review_member_id` INT(11) NOT NULL,
  `vote_review_review_id` INT(11) NOT NULL,
  PRIMARY KEY (`vote_review_id`),
  INDEX `fk_greenic_vote_review_greenic_member1_idx` (`vote_review_member_id` ASC),
  INDEX `fk_greenic_vote_review_greenic_review1_idx` (`vote_review_review_id` ASC),
  CONSTRAINT `fk_greenic_vote_review_greenic_member1`
    FOREIGN KEY (`vote_review_member_id`)
    REFERENCES `greenic_db`.`greenic_member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_greenic_vote_review_greenic_review1`
    FOREIGN KEY (`vote_review_review_id`)
    REFERENCES `greenic_db`.`greenic_review` (`review_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
